k: 30
model_name: car_k30_f16-Km3-5 # cf: cluster feature / if: image feature
generator_path: ./checkpoint/generators/stylegan2-car-config-f.pt
model_path: ./checkpoint/car_512x512/car_c4_5_f16_epoch7_best.pt
n_samples: 1 #./RFM_latentCLR/id1-i0-w600-norm301.878265-imgLoss2.196582.pt # 30 #./checkpoint/latent_code.npy  #id5_norm376.pt  #id2_norm375.pt #./checkpoint/latent_code.npy #./checkpoint/real_img/id10-i0-w1900-norm373.856293-imgLoss1.587639.pt 
save_single_imgs: true
sample_random: false
seed: 444 # 77249920 # 3
model:
  size: 512
  _target_: model.NonlinearConditional
  normalize: true
  alpha: 0.1
  depth: 3
  final_ac: false
generator:
  _target_: models.generators.stylegan2.stylegan2_wrap.StyleGAN2Generator
  device: cuda
  truncation: 0.7 # 0.85 for real image truncation = 1
  class_name: car
  use_w: true
  #feature_layer: convs.1 # conv1: 4*4 , [convs.0, convs.1] : 8*8,  [convs.2, convs.3] : 16*16, [convs.4, convs.5] : 32*32,  [convs.6, convs.7] : 64*64
image_size: 512
n_dirs: -1  #30  # -1: all, or list [33,34] : omegaconf.listconfig.ListConfig
alphas:
# - -150
# - -200
# - -250
# - -300
# - -350
# - -450
# - -300
# - -150
# - -200
# # - 250
# - -300
# # - 350
#- -400
# - -300
# - -200
# - -160
# - -150
# - -140
# - -130
# - -120
# - -110
# - -100
# - -90
# - -80
# - -70
# - -60
# - -50
# - -45
# - -40
# - -35
# - -30
# - -20
# - -10
# - -5
# - -2.5
# - -1.5
# # - -12.5
# - -10
# - -20
# # - 7.5
# - 20
# - 10
# - 1.5
# - 2.5
# - 5
# - 10
# # - 15
# - 20
# # - 25
# - 30
# - 35
# - 40
# - 45
# - 50
# - 60
# - 70
# - 80
# - 90
# - 100
# # - 110
# # - 120
# # - 130
# # - 140
# # - 150
# # - 160

# - -450
# - -300
# - -150
# - -75

# - -70

# - -50

# - -800
# - -600
# - -500
# - -400
# # - -300
# - -200
- -150
# - -125
- -100
# - -75
- -50
# - -25
# - -10

# - 10
# - 25
- 50
# - 75
- 100
# - 125
- 150
# - 200
# # - 300
# - 400
# - 500
# - 600
# - 800


feed_layers:
# - 0 # hair [200,360]
#- 1 # 4x4 hair-shape, face-shape  [80,240] (head-zoom) pose 
#- 2 # eyeglasses, pose, hair-shape, face-shape, age, Gender
#- 3 # 8x8 hair, face, identity, age,Gender, Mouth, Eyeglasses,   face-shape, xiaba, smile, pose, hair_more
#- 4 # hair, mouth-shape face-shape [20,80] @@@ smile, mouth(related-expression or hair-man)  mouth-shape face-shape  bald

#- 5 # 16x16 expression [feeling, mood] mouth-shape&color eye brow
#- 6 # eye-shape, brow-shape 6-7  [20,40,80] face-color Beard-shape age
- 7 # 32x32 hair&eye [only man] face-color hair-color
#- 8 # color-light: [hair, face, background]

#- 9 # 64x64 pupil
#- 10 # light [face] lips [red]
#- 11 # 128x128 color lips(a few)
#- 12 # color details: lips, face, clothes
#- 13 # 256x256 light, all img color

# - 14 # face color
# - 15 # 512x512 hair color
# - 16 # weak color&light for [face, background]
# - 17 # 1024x1024 background


